// <auto-generated />
using System;
using CustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240722184125_SeedAgents")]
    partial class SeedAgents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Entities.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgentId");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            AgentId = 1,
                            Name = "Agent One",
                            Password = "AQAAAAIAAYagAAAAEKjt9ShHhDiqGEJWk2zhqgXCn84gEeYsjElwkgs2G7uQCJ9OBhKajKd3DfKcCcSuQA==",
                            Username = "agent1"
                        },
                        new
                        {
                            AgentId = 2,
                            Name = "Agent Two",
                            Password = "AQAAAAIAAYagAAAAEHTUAruJASBw/I8Pzrf/Oeh5DPVhMz2CtN+VGT8TfVOCDMgUUCKEIlwMvIqRaMYRQQ==",
                            Username = "agent2"
                        },
                        new
                        {
                            AgentId = 3,
                            Name = "Agent Three",
                            Password = "AQAAAAIAAYagAAAAEO2ensguN3s1qYZv8O3rxJlq1rzug/OBD3OTBGnsOZtMNf2LGhxQ+5Ra/URLDthnLw==",
                            Username = "agent3"
                        },
                        new
                        {
                            AgentId = 4,
                            Name = "Agent Four",
                            Password = "AQAAAAIAAYagAAAAEPag72ZcnJmBl6cZzv3q4dmgXX1TtiFDAm64m0EAiQXNd+6hLMUueuru8f/MOOkZjQ==",
                            Username = "agent4"
                        },
                        new
                        {
                            AgentId = 5,
                            Name = "Agent Five",
                            Password = "AQAAAAIAAYagAAAAEBZdxYRKYLZejbKD2IJMAMVU7aGmqZf6Jj4NaTo1YzKNz3nk9l1noDnL/4ddrcbGaQ==",
                            Username = "agent5"
                        });
                });

            modelBuilder.Entity("CustomerService.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CouponEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CouponStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountCoupon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("CustomerService.Entities.Discount", b =>
                {
                    b.HasOne("CustomerService.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });
#pragma warning restore 612, 618
        }
    }
}
