// <auto-generated />
using System;
using CustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Entities.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            AgentId = 1,
                            Email = "agent1@example.com",
                            Name = "Agent One",
                            Password = "AQAAAAIAAYagAAAAEDd+HE+JFrQT8KjI5fzbwlqhe3t9sPnXCM4CSXI981R/Ttr4ZCwLOE2eK0XoipP6kA==",
                            Username = "agent1"
                        },
                        new
                        {
                            AgentId = 2,
                            Email = "agent2@example.com",
                            Name = "Agent Two",
                            Password = "AQAAAAIAAYagAAAAEITDww9U3iWycyWoeRyHMLlo9Ey0m92gM/2P0wYiGWobnGDJlCF/NGgxMKYHXneKyw==",
                            Username = "agent2"
                        },
                        new
                        {
                            AgentId = 3,
                            Email = "agent3@example.com",
                            Name = "Agent Three",
                            Password = "AQAAAAIAAYagAAAAECZti7b9lI2EV0OrKbqDeSv6Bd43AI04XaB2SUch5RtWZQLNiwlP3pI2/hdLIqmicw==",
                            Username = "agent3"
                        },
                        new
                        {
                            AgentId = 4,
                            Email = "agent4@example.com",
                            Name = "Agent Four",
                            Password = "AQAAAAIAAYagAAAAEAb8/CeIi5vnt10JZGUQKedYbNw6pxJ97EbQmpyj1LchCcSDyTKVVwaWtTqXT+Drdg==",
                            Username = "agent4"
                        },
                        new
                        {
                            AgentId = 5,
                            Email = "agent5@example.com",
                            Name = "Agent Five",
                            Password = "AQAAAAIAAYagAAAAEBZ6S2xW2nUHG3DBUs1is7lH+qfHmMg5pMLA38Bp2tH0o0ktwd6I85seei6apctNsg==",
                            Username = "agent5"
                        });
                });

            modelBuilder.Entity("CustomerService.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CouponEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CouponStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountCoupon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("CustomerService.Entities.Discount", b =>
                {
                    b.HasOne("CustomerService.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });
#pragma warning restore 612, 618
        }
    }
}
